export const authTypes = {
    OAUTH_START: 'AUTH_STARTING',
    OAUTH_SUCCESS: 'AUTH_SUCCESS',
<<<<<<< HEAD
    OAUTH_FAIL: 'AUTH_FAIL',
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN__SUCCESS',
    LOGIN_FAIL: 'LOGIN__FAIL'
=======
    OAUTH_FAIL: 'AUTH_FAIL'
};

export const groupTypes = {
    ADD_GROUP_START: "ADD_GROUP_START",
    ADD_GROUP_SUCCESS: "ADD_GROUP_SUCCESS",
    ADD_GROUP_FAILURE: "ADD_GROUP_FAILURE",
    
    FETCH_GROUPS_START: "FETCH_GROUPS_START",
    FETCH_GROUPS_SUCCESS: "FETCH_GROUPS_SUCCESS",
    FETCH_GROUPS_FAILURE: "FETCH_GROUPS_FAILURE",
    
    UPDATE_GROUP_START: "UPDATE_GROUP_START",
    UPDATE_GROUP_SUCCESS: "UPDATE_GROUP_SUCCESS",
    UPDATE_GROUP_FAILURE: "UPDATE_GROUP_FAILURE",
    
    DELETE_GROUP_START: "DELETE_GROUP_START",
    DELETE_GROUP_SUCCESS: "DELETE_GROUP_SUCCESS",
    DELETE_GROUP_FAILURE: "DELETE_GROUP_FAILURE"
>>>>>>> 9d55577319eec988f8b7022b3d1b4240a3cea933
};