export const authTypes = {
    OAUTH_START: 'AUTH_STARTING',
    OAUTH_SUCCESS: 'AUTH_SUCCESS',
    OAUTH_FAIL: 'AUTH_FAIL',
    REGISTER_START: 'REGISTER_START',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    GOOGLE_START: 'GOOGLE_START',
    GOOGLE_SUCCESS: 'GOOGLE_SUCCESS',
    GOOGLE_FAIL: 'GOOGLE_FAIL'
};